name: Update card status

on:
  push:

jobs:
  updateCardStatus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Get branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: get_branch

      - name: Get Database row
        run: |
          curl -X POST 'https://api.notion.com/v1/databases/3281190b33184642bf5b63fed1b7e69c/query' \
            -H 'Authorization: Bearer ${{ secrets.JIJI_NOTION_API_KEY }}' \
            -H 'Notion-Version: 2022-06-28' \
            -H "Content-Type: application/json" \
          --data '{
            "filter": {
              "property": "id",
              "number": {
                "equals": 2
              }
            }
          }' -o row.json

      - name: Set database id
        id: database_id
        run: echo "::set-output name=id::$(cat row.json)"

      - name: Update database row
        run: |
          curl https://api.notion.com/v1/pages/ \
            -H 'Authorization: Bearer secret_BQAKVYAxhk8bzO97AT5UPYHTjGm4XjNeTreGAsH1MUW' \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            -X PATCH \
          --data '{
            "parent": { "database_id": ${{steps.database_id.outputs.id}} },
            "properties": {
              "status": { "select": "abc" }
            }
          }'
