name: New discussion notification

on:
  discussion:
    types:
      - created
      - answered

jobs:
  slackNotification:
    runs-on: ubuntu-latest

    steps:
      - name: Get Title of discussion
        id: get-title
        run: |
          echo "::set-output name=title::${{ github.event.action == 'created' && '새로운 디스커션에 의견을 남겨주세요!' || '디스커션의 결론이 정해졌어요! :judge:'}}"

      - name: Get contents of discussion
        run: |
          echo "${{ github.event.action == 'created' && github.event.discussion.body || github.event.answer.body }}" > temp.txt
          echo 'SLACK_MESSAGE<<EOF' >> $GITHUB_ENV
          head -n 5 temp.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Get current date
        id: get-date
        run: |
          echo ::set-output name=date::$(${{ github.event.discussion.createdAt }} +"%Y-%m-%d %H:%M")

      - name: Convert body of discussion to slack markdown
        uses: LoveToKnow/slackify-markdown-action@v1.0.0
        id: discussion-to-markdown
        with:
          text: "**[[${{github.event.discussion.category.name}}] ${{github.event.discussion.title}}](${{github.event.discussion.html_url}})** \n ${{env.SLACK_MESSAGE }}"

      - name: Notify new discussion
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: for-test
          SLACK_TITLE: ${{steps.get-title.outputs.title}}
          SLACK_MESSAGE: ${{steps.discussion-to-markdown.outputs.text}}
          SLACK_USERNAME: Take a look
          SLACK_COLOR: '#ffcd00'
          SLACK_ICON: https://user-images.githubusercontent.com/103918900/187191022-1baacdd8-6208-46df-b9a4-2c2081de4809.png
          SLACK_FOOTER: 'This discussion is created at ${{steps.get-date.outputs.date}}'
          MSG_MINIMAL: true
